name: tests
on: push
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Run tests with Maven
        run: mvn -B test --file pom.xml

  merge_pull_request:
    runs-on: ubuntu-latest
    needs: run_tests
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Set up Git
        run: git config --global user.email "actions@github.com" && git config --global user.name "GitHub Actions"
      - name: Merge pull request
        uses: pullreminders/merge-action@v0.14.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
