name: tests
on:
  push:
    branches:
      - master

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Run tests with Maven
        run: mvn -B test --file pom.xml

  merge_pull_request:
    runs-on: ubuntu-latest
    needs: run_tests
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Set up Git
        run: git config --global user.email "2022120067@github.com" && git config --global user.name "2022120067"
      - name: PR Merge
        uses: actions-cool/pr-merge@v0.0.1-beat
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
